services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: investimentos-sql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SenhaF0rte!2025
    ports:
      - "1433:1433"
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: investimentos-redis
    command: ["redis-server", "--requirepass", "MinhaSenhaForteLocalRedis123"]
    environment:
      - REDIS_PASSWORD=MinhaSenhaForteLocalRedis123
    ports:
      - "6379:6379"
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: investimentos-api
    ports:
      - "5000:80"
    depends_on:
      - sqlserver
      - redis
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=InvestimentosCaixa;User Id=sa;Password=SenhaF0rte!2025;TrustServerCertificate=True;
      - REDIS_CONNECTION=redis:6379,password=MinhaSenhaForteLocalRedis123,abortConnect=false
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
